#!/bin/sh

# Configure datbase
export DATABASE=$(pwd)/dredd.sqlite
rm $DATABASE
export DATABASE_URL=sqlite:///$DATABASE

# Sync the database
python manage.py migrate

# Run the dev server
python manage.py runserver --noreload &
sleep 1
PID=$!

# Run dredd
dredd apiary.apib http://localhost:8000 --hookfiles=dredd-hooks.js
RESULT=$?

kill -9 $PID
exit $RESULT

